language: cpp
sudo: false

matrix:
  include:
    - env: GCC_VERSION=4.9 BUILD_TYPE=Release
      os: linux
      addons: &gcc49
        apt:
          packages: g++-4.9
          sources: &sources
            - ubuntu-toolchain-r-test
    - env: GCC_VERSION=5 BUILD_TYPE=Release
      os: linux
      addons: &gcc5
        apt:
          packages: g++-5
          sources: *sources
    - env: BUILD_TYPE=Release
      os: osx
      osx_image: xcode6.4
      compiler: clang
    - env: BUILD_TYPE=Release
      os: osx
      osx_image: xcode8
      compiler: clang

install:
  - if [[ -n "$GCC_VERSION" ]]; then export CXX=g++-$GCC_VERSION CC=gcc-$GCC_VERSION; fi
  - export INSTALL_DIR=${HOME}/.local MAKEFLAGS="-j 2"
  - ./.travis/install.sh

before_script:
  - cd "${TRAVIS_BUILD_DIR}"
  - ./configure --build-type=${BUILD_TYPE}
  - make

script:
  - make check
